Default: &defaults
  database: appgent-ekiden-demo.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: appgent-ekiden-demo_test.sqlite3
  <<: *defaults

Staging:
  database: appgent-ekiden-demo_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: appgent-ekiden-demo_production.sqlite3
  poolsize: 100
  <<: *defaults
